// ──────────────────────────────────────────────────────────
// IPC command: generic workspace file read (Files tab)
// ──────────────────────────────────────────────────────────
//
// read_file({ cwd, path }) — reads a single file for the Files-tab viewer.
// The real logic lives in src/engine/files/read-file.ts so the remote
// workspace bridge (engine process) and this local IPC path share ONE
// implementation. See that file for the safety/bounds contract.
//
// H3 — the renderer supplies `cwd`. Left unchecked it was an arbitrary-file
// read primitive (`read_file({cwd:"~/.ssh", path:"id_rsa"})`). The fix is
// `cwdIsTrusted()` below: `cwd` MUST be the open project root OR live under the
// Zeros worktrees tree — every legitimate Files-tab cwd — and readWorkspaceFile
// then lexically + realpath-confines the read inside that root. Together those
// fully close the arbitrary-read hole.
//
// This is a LOCAL read on the owner's OWN machine, so it runs with `remote:false`
// (full access). The secret/credential denylist is the REMOTE boundary ONLY
// (remote/cloud clients hit it via the engine `file.read` op). An earlier H3
// hardening also forced `remote:true` here, which hid secret-named files
// (.npmrc, .env, …) that legitimately live INSIDE the project — even though
// (a) the read-only "Local main" trunk shows them anyway (it reads over the
// loopback bridge as a `local` client → remote:false) and (b) the Files TREE
// (git_list_files) already lists them. The only effect was a confusing
// "refusing … over a remote connection" error on a purely local worktree read,
// inconsistent with both Local main and the tree. See read-file.ts: the denylist
// is the remote boundary; the local Files tab keeps full access.
// ──────────────────────────────────────────────────────────

import fs from "node:fs";
import path from "node:path";
import { nativeImage } from "electron";
import {
  isInside,
  readWorkspaceFile,
  type ReadFileKind,
  type ReadFileResult,
} from "../../../src/engine/files/read-file";
import {
  writeWorkspaceFile,
  type WriteFileResult,
} from "../../../src/engine/files/write-file";
import { zerosWorkspacesRoot } from "../../../src/engine/db/paths";
import { currentRoot } from "../../sidecar";
import type { CommandHandler } from "../router";
import {
  containedThumbnailSize,
  probeImageDimensions,
} from "./image-dimensions";

export type { ReadFileKind, ReadFileResult, WriteFileResult };

const DEFAULT_THUMBNAIL_SIZE = 256;
const THUMBNAIL_SIZES = new Set([256, 512, 1024, 1536]);
const MAX_THUMBNAIL_SOURCE_BYTES = 100_000_000;
const MAX_THUMBNAIL_SOURCE_PIXELS = 160_000_000;
const MAX_DIRECT_DECODE_SOURCE_BYTES = 32_000_000;
const MAX_DIRECT_DECODE_SOURCE_PIXELS = 40_000_000;
const THUMBNAIL_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".bmp",
  ".ico",
  ".avif",
  ".svg",
]);

export type ReadImageThumbnailResult =
  | {
      kind: "image";
      path: string;
      /** Source byte size, useful for honest fallback/debug information. */
      bytes: number;
      width: number;
      height: number;
      /** Original dimensions from the bounded header probe. */
      sourceWidth: number;
      sourceHeight: number;
      /** EXIF transform the renderer must apply when the fallback decoder did
       * not orient the pixels itself. Omitted for already-oriented previews. */
      orientation?: number;
      /** Bounded PNG preview generated by Electron, never the source bytes. */
      dataUrl: string;
    }
  | {
      kind: "error" | "too-large";
      path: string;
      bytes: number;
      error: string;
    };

/** The renderer-supplied cwd must be the open project root or live under the
 *  Zeros worktrees tree — never an arbitrary host path. */
function cwdIsTrusted(cwd: string): boolean {
  const resolved = path.resolve(cwd);
  const roots = [currentRoot(), zerosWorkspacesRoot()].filter(
    (r): r is string => typeof r === "string" && r.length > 0,
  );
  return roots.some((root) => {
    const r = path.resolve(root);
    return resolved === r || resolved.startsWith(r + path.sep);
  });
}

function thumbnailFailure(
  relPath: string,
  error: string,
  bytes = 0,
): ReadImageThumbnailResult {
  return { kind: "error", path: relPath, bytes, error };
}

/** read_image_thumbnail({ cwd, path, maxDimension }) — decode a small native
 * preview for the Context canvas. This deliberately does not call
 * readWorkspaceFile: that API
 * serialises the complete source image (up to 5 MB) as base64, defeating the
 * thumbnail's memory/transport purpose. The command repeats the same trust,
 * lexical-containment, and realpath-containment gates, then passes the already
 * resolved real path to Electron so a symlink swap at the requested path
 * cannot redirect the decode after validation. */
export const readImageThumbnail: CommandHandler = async (args) => {
  const cwd = String(args.cwd ?? "");
  const rel = String(args.path ?? "");
  if (!cwd || !cwdIsTrusted(cwd)) {
    return thumbnailFailure(rel, "refusing to read outside the workspace");
  }
  if (!rel) return thumbnailFailure(rel, "missing path");
  const requestedDimension =
    args.maxDimension == null
      ? DEFAULT_THUMBNAIL_SIZE
      : Number(args.maxDimension);
  if (!THUMBNAIL_SIZES.has(requestedDimension)) {
    return thumbnailFailure(rel, "unsupported thumbnail size");
  }

  const root = path.resolve(cwd);
  const target = path.resolve(cwd, rel);
  if (!isInside(target, root)) {
    return thumbnailFailure(rel, "refusing to read outside the workspace");
  }
  if (!THUMBNAIL_EXTENSIONS.has(path.extname(target).toLowerCase())) {
    return thumbnailFailure(rel, "this file is not a supported image");
  }

  let realRoot: string;
  let realTarget: string;
  let bytes: number;
  try {
    realRoot = fs.realpathSync(root);
    realTarget = fs.realpathSync(target);
    if (!isInside(realTarget, realRoot)) {
      return thumbnailFailure(
        rel,
        "refusing to follow a symlink outside the workspace",
      );
    }
    const stat = fs.statSync(realTarget);
    if (!stat.isFile()) return thumbnailFailure(rel, "not a regular file");
    bytes = stat.size;
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    return thumbnailFailure(
      rel,
      code === "ENOENT"
        ? "file no longer exists on disk"
        : `cannot read image (${code ?? "unknown error"})`,
    );
  }

  if (bytes > MAX_THUMBNAIL_SOURCE_BYTES) {
    return {
      kind: "too-large",
      path: rel,
      bytes,
      error: "image is too large to thumbnail safely",
    };
  }

  // Probe only a bounded prefix. Supplying the source aspect ratio to the
  // macOS thumbnail service prevents it from baking a square stretch into the
  // bitmap; CSS object-fit cannot repair pixels that arrived distorted.
  const sourceSize = probeImageDimensions(realTarget, bytes);
  if (!sourceSize) {
    return thumbnailFailure(
      rel,
      "image dimensions could not be read safely",
      bytes,
    );
  }
  const sourcePixels = sourceSize.width * sourceSize.height;
  if (sourcePixels > MAX_THUMBNAIL_SOURCE_PIXELS) {
    return {
      kind: "too-large",
      path: rel,
      bytes,
      error: "image dimensions are too large to thumbnail safely",
    };
  }
  const requestedSize = containedThumbnailSize(sourceSize, requestedDimension);

  try {
    let image: Awaited<
      ReturnType<typeof nativeImage.createThumbnailFromPath>
    > | null = null;
    let usedDirectDecoder = false;
    try {
      // macOS/Windows ask the OS thumbnail service to avoid decoding the full
      // source into the renderer. Unsupported platforms reject and fall back
      // to NativeImage's PNG/JPEG decoder below.
      image = await nativeImage.createThumbnailFromPath(
        realTarget,
        requestedSize,
      );
    } catch {
      // A platform without a thumbnail provider reaches the bounded direct
      // fallback below.
    }
    // Some platform providers report failure as an empty image rather than
    // rejecting. Keep the fallback much tighter than the OS-thumbnail path:
    // NativeImage's direct decoder may materialise the complete pixel buffer.
    if (!image || image.isEmpty()) {
      if (
        bytes > MAX_DIRECT_DECODE_SOURCE_BYTES ||
        sourcePixels > MAX_DIRECT_DECODE_SOURCE_PIXELS
      ) {
        return {
          kind: "too-large",
          path: rel,
          bytes,
          error: "image is too large for the safe decoder fallback",
        };
      }
      image = nativeImage.createFromPath(realTarget);
      usedDirectDecoder = true;
    }
    if (image.isEmpty()) {
      return thumbnailFailure(rel, "image format could not be decoded", bytes);
    }
    // OS preview caches can legally return a much smaller bitmap than the
    // requested close-up size. Treating that response as a 1024/1536 preview
    // permanently scales blur in the renderer. For sources inside the strict
    // direct-decoder budget, retry from the original pixels; for genuinely
    // huge sources retain the safe OS preview instead of risking a large
    // allocation in Electron main.
    let initialSize = image.getSize();
    const providerLongestEdge = Math.max(
      initialSize.width,
      initialSize.height,
    );
    const requestedLongestEdge = Math.max(
      requestedSize.width,
      requestedSize.height,
    );
    const providerIsUndersized =
      !usedDirectDecoder &&
      providerLongestEdge < requestedLongestEdge * 0.75 &&
      providerLongestEdge < Math.max(sourceSize.width, sourceSize.height);
    if (
      providerIsUndersized &&
      bytes <= MAX_DIRECT_DECODE_SOURCE_BYTES &&
      sourcePixels <= MAX_DIRECT_DECODE_SOURCE_PIXELS
    ) {
      try {
        const sourceImage = nativeImage.createFromPath(realTarget);
        if (!sourceImage.isEmpty()) {
          image = sourceImage;
          usedDirectDecoder = true;
          initialSize = image.getSize();
        }
      } catch {
        // Keep the valid bounded OS preview when the optional quality retry
        // cannot decode this format.
      }
    }
    const requestedRatio = requestedSize.width / requestedSize.height;
    const initialRatio = initialSize.width / initialSize.height;
    // A decoded JPEG whose EXIF orientation swaps its axes has the reciprocal
    // ratio. Electron documents that NativeImage itself does not apply EXIF;
    // forcing that bitmap into the display-oriented width AND height would
    // visibly squeeze it. Preserve those pixels and let the contained card
    // present the decoder's honest ratio.
    const reciprocalRatio = 1 / requestedRatio;
    const isReciprocalOrientation =
      sourceSize.orientation != null &&
      sourceSize.orientation >= 5 &&
      sourceSize.orientation <= 8 &&
      Number.isFinite(initialRatio) &&
      Math.abs(initialRatio - reciprocalRatio) / reciprocalRatio <= 0.01;
    const needsCssOrientation =
      sourceSize.orientation != null &&
      (usedDirectDecoder || isReciprocalOrientation);
    if (
      !isReciprocalOrientation &&
      (initialSize.width > requestedSize.width ||
        initialSize.height > requestedSize.height ||
        !Number.isFinite(initialRatio) ||
        Math.abs(initialRatio - requestedRatio) / requestedRatio > 0.01)
    ) {
      // Electron documents that a two-axis resize uses both dimensions. Here
      // they carry the probed SOURCE ratio, so this corrects any platform
      // thumbnail service that returned a square/stretched bitmap.
      image = image.resize({ ...requestedSize, quality: "good" });
    } else if (
      initialSize.width > requestedDimension ||
      initialSize.height > requestedDimension
    ) {
      image = image.resize({
        ...(initialSize.width >= initialSize.height
          ? { width: requestedDimension }
          : { height: requestedDimension }),
        quality: "good",
      });
    }
    const size = image.getSize();
    if (image.isEmpty() || size.width <= 0 || size.height <= 0) {
      return thumbnailFailure(rel, "image format could not be decoded", bytes);
    }
    return {
      kind: "image",
      path: rel,
      bytes,
      width: size.width,
      height: size.height,
      sourceWidth: sourceSize.width,
      sourceHeight: sourceSize.height,
      ...(needsCssOrientation ? { orientation: sourceSize.orientation } : {}),
      dataUrl: image.toDataURL(),
    };
  } catch (err) {
    return thumbnailFailure(
      rel,
      err instanceof Error ? err.message : "image thumbnail failed",
      bytes,
    );
  }
};

export const readFile: CommandHandler = (args) => {
  const cwd = String(args.cwd ?? "");
  const rel = String(args.path ?? "");
  if (!cwd || !cwdIsTrusted(cwd)) {
    return {
      kind: "error",
      path: rel,
      bytes: 0,
      error: "refusing to read outside the workspace",
    } satisfies ReadFileResult;
  }
  // Local read on the owner's machine → remote:false (full access). The
  // arbitrary-read threat is closed by cwdIsTrusted() + readWorkspaceFile's
  // containment checks; the secret denylist stays a REMOTE-only boundary so
  // this stays consistent with Local main and the Files tree (which both show
  // these files). Do NOT pass remote:true here — see the header note.
  return readWorkspaceFile(cwd, rel, { remote: false });
};

/** write_file({ cwd, path, content }) — writes a single file for the Files-tab
 *  editor (Edit mode). Same trust boundary as readFile: `cwd` MUST be the open
 *  project root or under the Zeros worktrees tree, then writeWorkspaceFile
 *  lexically + realpath-confines the write inside that root. Local write on the
 *  owner's machine → remote:false. */
export const writeFile: CommandHandler = (args) => {
  const cwd = String(args.cwd ?? "");
  const rel = String(args.path ?? "");
  const content = typeof args.content === "string" ? args.content : null;
  if (!cwd || !cwdIsTrusted(cwd)) {
    return {
      kind: "error",
      path: rel,
      bytes: 0,
      error: "refusing to write outside the workspace",
    } satisfies WriteFileResult;
  }
  if (content === null) {
    return {
      kind: "error",
      path: rel,
      bytes: 0,
      error: "missing content",
    } satisfies WriteFileResult;
  }
  return writeWorkspaceFile(cwd, rel, content, { remote: false });
};
