/**
 * Shape-first dot-matrix sprites for the five-story loader.
 *
 * The reference animation keeps every dot on a regular grid and animates
 * luminance across a recognizable silhouette. These poses follow that rule:
 * most cells stay fixed, while only storytelling landmarks (legs, pupils,
 * oar, steam, the rising sun) change between poses.
 *
 * The matrix is authored 24px-first: 12 columns give an exact 2px dot pitch
 * inside a 24 x 24 canvas, so every silhouette stays readable at true size.
 */
(function registerStoryJourney(root) {
  "use strict";

  const GRID_WIDTH = 12;
  const GRID_HEIGHT = 12;
  const VIEW_SIZE = 12;
  const ACTION_FRAMES = 16;
  const TRANSITION_FRAMES = 4;

  const CHARACTER_RADIUS = Object.freeze({
    "#": 1,
    O: 1.3,
    o: 0.8,
  });

  function clamp(value, minimum, maximum) {
    return Math.min(maximum, Math.max(minimum, value));
  }

  function smoothstep(value) {
    const progress = clamp(value, 0, 1);
    return progress * progress * (3 - 2 * progress);
  }

  function rows(value, label) {
    const result = value.trim().split("\n");
    if (result.length !== GRID_HEIGHT) {
      throw new Error(
        `${label} must have ${GRID_HEIGHT} rows; received ${result.length}.`,
      );
    }
    for (const [index, row] of result.entries()) {
      if (row.length !== GRID_WIDTH) {
        throw new Error(
          `${label} row ${index + 1} must have ${GRID_WIDTH} cells; received ${row.length}.`,
        );
      }
    }
    return result;
  }

  function cellsFromMasks(label, ...masks) {
    const cells = new Map();
    for (const mask of masks) {
      for (let y = 0; y < mask.length; y += 1) {
        for (let x = 0; x < mask[y].length; x += 1) {
          const character = mask[y][x];
          if (!(character in CHARACTER_RADIUS)) continue;
          const id = `cell-${String(x).padStart(2, "0")}-${String(y).padStart(2, "0")}`;
          const existing = cells.get(id);
          const radius = CHARACTER_RADIUS[character];
          if (!existing || radius > existing.radius) {
            cells.set(id, {
              alpha: 1,
              id,
              radius,
              x: x - (GRID_WIDTH - 1) / 2,
              y: y - (GRID_HEIGHT - 1) / 2,
            });
          }
        }
      }
    }
    return Object.freeze(
      [...cells.values()]
        .sort((first, second) => first.y - second.y || first.x - second.x)
        .map(Object.freeze),
    );
  }

  function poseSet(sceneId, baseSource, motionSources) {
    const base = rows(baseSource, `${sceneId} base`);
    return Object.freeze(
      motionSources.map((source, index) =>
        cellsFromMasks(
          `${sceneId} pose ${index + 1}`,
          base,
          rows(source, `${sceneId} motion ${index + 1}`),
        ),
      ),
    );
  }

  const catMouse = poseSet(
    "cat-mouse",
    `............
............
....#.#.....
o...###.....
.o..####....
.#######....
.######.....
..##..##....
............
..........O.
........o##o
............`,
    [
      `............
............
............
............
............
............
............
............
..#....#....
.##....##...
O.......O...
............`,
      `............
............
............
............
............
............
............
............
...#..#.....
...##.##....
....O.O.....
............`,
      `............
............
............
............
............
............
............
............
..#.....#...
.##....##...
.O.....O....
............`,
      `............
............
............
............
............
............
............
............
..#...#.....
..#...#.....
..O...O.....
............`,
    ],
  );

  const eyesRolling = poseSet(
    "eyes-rolling",
    `............
............
............
............
..##....##..
.#..#..#..#.
.#..#..#..#.
.#..#..#..#.
..##....##..
............
............
............`,
    [
      `............
............
............
............
............
..o.....o...
..O.....O...
..o.....o...
............
............
............
............`,
      `............
............
............
............
............
...o.....o..
...O.....O..
...o.....o..
............
............
............
............`,
      `............
............
............
............
............
..o.....o...
..O.....O...
..o.....o...
............
............
............
............`,
      `............
............
............
............
............
...o.....o..
...O.....O..
...o.....o..
............
............
............
............`,
    ],
  );

  const rowerBoat = poseSet(
    "rower-boat",
    `............
............
....O.......
...###......
...##.......
..###.......
.##########.
..########..
....####....
............
............
.o..o..o..o.`,
    [
      `..........o.
.........#..
........#...
.......#....
.....##.....
............
............
............
............
............
............
............`,
      `............
............
............
.........##O
......###...
.....#......
............
............
............
............
............
............`,
      `............
............
............
............
.....##.....
.......##...
.........#..
..........O.
............
............
............
............`,
      `............
..........o.
........##..
.......#....
.....##.....
............
............
............
............
............
............
............`,
    ],
  );

  const trainSteam = poseSet(
    "train-steam",
    `............
............
.......##...
.####..##...
.#..#..##...
.#..#######.
.##########O
.##########.
..O..O..O...
............
............
............`,
    [
      `......o.....
........o...
............
............
............
............
............
............
............
............
............
............`,
      `....o.......
.......O....
............
............
............
............
............
............
............
............
............
............`,
      `...o....o...
......o.....
............
............
............
............
............
............
............
............
............
............`,
      `.....o......
........o...
............
............
............
............
............
............
............
............
............
............`,
    ],
  );

  const mountainSunrise = poseSet(
    "mountain-sunrise",
    `............
............
............
............
............
..#......#..
.###....###.
#####..#####
############
............
............
............`,
    [
      `............
............
............
............
............
............
............
.....OO.....
............
............
............
............`,
      `............
............
............
............
............
............
.....OO.....
.....OO.....
............
............
............
............`,
      `............
............
............
............
............
.....OO.....
.....OO.....
............
............
............
............
............`,
      `............
............
.....oo.....
...o....o...
.....OO.....
.....OO.....
............
............
............
............
............
............`,
    ],
  );

  const sceneDefinitions = Object.freeze([
    Object.freeze({
      ariaLabel: "A tiny dotted cat chasing a small mouse",
      code: "A",
      description:
        "The cat's pointed ears and body stay fixed while its legs sprint after the fleeing mouse.",
      id: "cat-mouse",
      name: "Cat + mouse",
      nextDescription:
        "A four-frame relay wipe hands the chase to a pair of rolling eyes.",
      poses: catMouse,
      verbs: "Chase · sprint · scurry",
    }),
    Object.freeze({
      ariaLabel: "Two tiny dotted eyes rolling left and right",
      code: "B",
      description:
        "Two fixed eye outlines hold still while the oversized pupils roll from side to side.",
      id: "eyes-rolling",
      name: "Rolling eyes",
      nextDescription:
        "A blink-quick wipe turns the gaze toward the rower's first stroke.",
      poses: eyesRolling,
      verbs: "Glance · roll · dart",
    }),
    Object.freeze({
      ariaLabel: "A tiny dotted rower pulling an oar in a boat",
      code: "C",
      description:
        "The hull and rower remain fixed landmarks while the long oar sweeps through four angles.",
      id: "rower-boat",
      name: "Rower + boat",
      nextDescription:
        "The oar rises toward the chimney as the boat is replaced by the locomotive.",
      poses: rowerBoat,
      verbs: "Reach · pull · glide",
    }),
    Object.freeze({
      ariaLabel: "A tiny dotted steam locomotive with drifting smoke",
      code: "D",
      description:
        "A classic engine profile anchors the scene while steam puffs drift left.",
      id: "train-steam",
      name: "Train + steam",
      nextDescription:
        "The drifting steam clears into a mountain valley at dawn.",
      poses: trainSteam,
      verbs: "Chug · roll · billow",
    }),
    Object.freeze({
      ariaLabel: "A tiny dotted sun rising between two mountains",
      code: "E",
      description:
        "Two mountain silhouettes stay fixed while the sun climbs out of the valley and rays appear.",
      id: "mountain-sunrise",
      name: "Mountain sunrise",
      nextDescription:
        "The risen sun hands the loop back to the cat-and-mouse chase.",
      poses: mountainSunrise,
      verbs: "Rise · glow · beam",
    }),
  ]);

  function poseMap(pose) {
    return new Map(pose.map((entry) => [entry.id, entry]));
  }

  function interpolatedMotionPose(keyPoses, frame) {
    const exactKey =
      (frame / Math.max(1, ACTION_FRAMES - 1)) * (keyPoses.length - 1);
    const fromIndex = Math.floor(exactKey);
    const toIndex = Math.min(keyPoses.length - 1, fromIndex + 1);
    const blend = smoothstep(exactKey - fromIndex);
    const from = poseMap(keyPoses[fromIndex]);
    const to = poseMap(keyPoses[toIndex]);
    const ids = new Set([...from.keys(), ...to.keys()]);
    const result = [];

    for (const id of ids) {
      const fromCell = from.get(id);
      const toCell = to.get(id);
      const anchor = fromCell || toCell;
      const alpha = (fromCell ? 1 - blend : 0) + (toCell ? blend : 0);
      if (alpha < 0.025) continue;
      result.push(
        Object.freeze({
          ...anchor,
          alpha: clamp(alpha, 0, 1),
          radius:
            (fromCell?.radius || anchor.radius) * (1 - blend) +
            (toCell?.radius || anchor.radius) * blend,
        }),
      );
    }

    return Object.freeze(
      result.sort((first, second) => first.y - second.y || first.x - second.x),
    );
  }

  function relayWipePose(fromPose, toPose, progress) {
    const from = poseMap(fromPose);
    const to = poseMap(toPose);
    const ids = new Set([...from.keys(), ...to.keys()]);
    const eased = smoothstep(progress);
    const threshold = -9 + eased * 18;
    const feather = 1.2;
    const result = [];

    for (const id of ids) {
      const fromCell = from.get(id);
      const toCell = to.get(id);
      const anchor = fromCell || toCell;
      const diagonal = anchor.x + anchor.y * 0.32;
      const toAlpha = clamp(
        (threshold - diagonal + feather) / (feather * 2),
        0,
        1,
      );
      const fromAlpha = 1 - toAlpha;
      const alpha = Math.max(fromCell ? fromAlpha : 0, toCell ? toAlpha : 0);
      if (alpha < 0.04) continue;
      result.push(
        Object.freeze({
          ...anchor,
          alpha,
          radius: Math.max(fromCell?.radius || 0, toCell?.radius || 0),
        }),
      );
    }

    return Object.freeze(
      result.sort((first, second) => first.y - second.y || first.x - second.x),
    );
  }

  function buildJourney() {
    const poses = [];
    const frameScenes = [];
    const scenes = [];

    for (
      let sceneIndex = 0;
      sceneIndex < sceneDefinitions.length;
      sceneIndex += 1
    ) {
      const scene = sceneDefinitions[sceneIndex];
      const nextScene =
        sceneDefinitions[(sceneIndex + 1) % sceneDefinitions.length];
      const startFrame = poses.length;

      for (let frame = 0; frame < ACTION_FRAMES; frame += 1) {
        poses.push(interpolatedMotionPose(scene.poses, frame));
        frameScenes.push(
          Object.freeze({
            actionProgress: frame / ACTION_FRAMES,
            label: `${scene.code} · ${scene.name}`,
            nextSceneId: nextScene.id,
            sceneId: scene.id,
            sceneIndex,
            transition: false,
          }),
        );
      }

      const transitionStartFrame = poses.length;
      const fromPose = poses[poses.length - 1];
      const toPose = nextScene.poses[0];
      for (let frame = 0; frame < TRANSITION_FRAMES; frame += 1) {
        const transitionProgress = (frame + 1) / (TRANSITION_FRAMES + 1);
        poses.push(relayWipePose(fromPose, toPose, transitionProgress));
        frameScenes.push(
          Object.freeze({
            actionProgress: 1,
            label: `${scene.name} → ${nextScene.name}`,
            nextSceneId: nextScene.id,
            sceneId: scene.id,
            sceneIndex,
            transition: true,
            transitionProgress,
          }),
        );
      }

      scenes.push(
        Object.freeze({
          ...scene,
          actionFrameCount: ACTION_FRAMES,
          endFrame: poses.length - 1,
          nextSceneId: nextScene.id,
          startFrame,
          transitionFrameCount: TRANSITION_FRAMES,
          transitionStartFrame,
        }),
      );
    }

    const dotCounts = poses.map((pose) => pose.length);
    return Object.freeze({
      ariaLabel:
        "A continuous dotted loader showing a cat chasing a mouse, rolling eyes, a rower and boat, a steam train, then a sun rising between two mountains",
      code: "ONE",
      description:
        "Five recognizable dot-matrix stories connected by quick relay wipes and one traveling shimmer.",
      dotCount: Math.max(...dotCounts),
      dotCountRange: Object.freeze([
        Math.min(...dotCounts),
        Math.max(...dotCounts),
      ]),
      dotRadius: 0.4,
      duration: 8000,
      frameCount: poses.length,
      frameScenes: Object.freeze(frameScenes),
      id: "five-story-journey",
      keyPoseCount: sceneDefinitions.length,
      name: "Five-story dot-matrix journey",
      poses: Object.freeze(poses),
      sceneFrameCount: ACTION_FRAMES + TRANSITION_FRAMES,
      scenes: Object.freeze(scenes),
      shimmerCycles: sceneDefinitions.length,
      viewHeight: VIEW_SIZE,
      viewWidth: VIEW_SIZE,
    });
  }

  const journey = buildJourney();

  root.StoryShimmerLibrary = Object.freeze({
    defaultStoryId: journey.id,
    list: Object.freeze([journey]),
    stories: Object.freeze({ [journey.id]: journey }),
  });
})(window);
