import type { CodexCapabilityOperation } from "@zeros/protocol/messages";

import type { CodexAppServerHandle } from "./app-server";

/** Exhaustive, typed dispatch from Zeros' public capability allowlist to the
 * generated app-server client. There is intentionally no generic request()
 * fallback: adding an operation requires a reviewed protocol edit and test. */
export function invokeCodexCapability(
  runtime: CodexAppServerHandle,
  operation: CodexCapabilityOperation,
  params: unknown,
): Promise<unknown> {
  const p = params as never;
  switch (operation) {
    case "thread.fork":
      return runtime.forkThread(p);
    case "thread.goal.set":
      return runtime.setThreadGoal(p);
    case "thread.goal.get":
      return runtime.getThreadGoal(p);
    case "thread.goal.clear":
      return runtime.clearThreadGoal(p);
    case "thread.list":
      return runtime.listThreads(p);
    case "thread.read":
      return runtime.readThread(p);
    case "thread.turns.list":
      return runtime.listThreadTurns(p);
    case "thread.items.list":
      return runtime.listThreadItems(p);
    case "thread.search":
      return runtime.searchThreads(p);
    case "thread.searchOccurrences":
      return runtime.searchThreadOccurrences(p);
    case "thread.loaded.list":
      return runtime.listLoadedThreads(p);
    case "thread.backgroundTerminals.list":
      return runtime.listBackgroundTerminals(p);
    case "thread.backgroundTerminals.clean":
      return runtime.cleanBackgroundTerminals(p);
    case "thread.backgroundTerminals.terminate":
      return runtime.terminateBackgroundTerminal(p);
    case "thread.metadata.update":
      return runtime.updateThreadMetadata(p);
    case "thread.memoryMode.set":
      return runtime.setThreadMemoryMode(p);
    case "thread.guardianDeniedAction.approve":
      return runtime.approveGuardianDeniedAction(p);
    case "memory.reset":
      return runtime.resetMemory();
    case "thread.realtime.start":
      return runtime.startThreadRealtime(p);
    case "thread.realtime.appendAudio":
      return runtime.appendThreadRealtimeAudio(p);
    case "thread.realtime.appendText":
      return runtime.appendThreadRealtimeText(p);
    case "thread.realtime.appendSpeech":
      return runtime.appendThreadRealtimeSpeech(p);
    case "thread.realtime.stop":
      return runtime.stopThreadRealtime(p);
    case "thread.realtime.voices.list":
      return runtime.listThreadRealtimeVoices(p);
    case "skills.list":
      return runtime.listSkills(p);
    case "skills.extraRoots.set":
      return runtime.setSkillExtraRoots(p);
    case "skills.config.write":
      return runtime.writeSkillsConfig(p);
    case "hooks.list":
      return runtime.listHooks(p);
    case "mcp.oauth.login":
      return runtime.loginMcpServer(p);
    case "mcp.reload":
      return runtime.reloadMcpServers();
    case "mcp.status.list":
      return runtime.listMcpServerStatus(p);
    case "mcp.resource.read":
      return runtime.readMcpResource(p);
    case "mcp.tool.call":
      return runtime.callMcpTool(p);
    case "apps.list":
      return runtime.listApps(p);
    case "apps.read":
      return runtime.readApp(p);
    case "apps.installed":
      return runtime.installedApps(p);
    case "plugins.list":
      return runtime.listPlugins(p);
    case "plugins.installed":
      return runtime.installedPlugins(p);
    case "plugins.read":
      return runtime.readPlugin(p);
    case "plugins.skill.read":
      return runtime.readPluginSkill(p);
    case "plugins.install":
      return runtime.installPlugin(p);
    case "plugins.uninstall":
      return runtime.uninstallPlugin(p);
    case "marketplaces.add":
      return runtime.addMarketplace(p);
    case "marketplaces.remove":
      return runtime.removeMarketplace(p);
    case "marketplaces.upgrade":
      return runtime.upgradeMarketplace(p);
    case "pluginShares.save":
      return runtime.savePluginShare(p);
    case "pluginShares.updateTargets":
      return runtime.updatePluginShareTargets(p);
    case "pluginShares.list":
      return runtime.listPluginShares(p);
    case "pluginShares.checkout":
      return runtime.checkoutPluginShare(p);
    case "pluginShares.delete":
      return runtime.deletePluginShare(p);
    case "account.read":
      return runtime.readAccount(p);
    case "account.rateLimits.read":
      return runtime.readAccountRateLimits();
    case "account.usage.read":
      return runtime.readAccountUsage();
    case "account.workspaceMessages.read":
      return runtime.readWorkspaceMessages();
    case "account.login.start":
      return runtime.startAccountLogin(p);
    case "account.login.cancel":
      return runtime.cancelAccountLogin(p);
    case "account.logout":
      return runtime.logoutAccount();
    case "account.rateLimitResetCredit.consume":
      return runtime.consumeRateLimitResetCredit(p);
    case "account.sendAddCreditsNudgeEmail":
      return runtime.sendAddCreditsNudgeEmail(p);
    case "config.read":
      return runtime.readConfig(p);
    case "config.value.write":
      return runtime.writeConfigValue(p);
    case "config.batch.write":
      return runtime.writeConfigBatch(p);
    case "config.requirements.read":
      return runtime.readConfigRequirements();
    case "externalAgentConfig.detect":
      return runtime.detectExternalAgentConfigs(p);
    case "externalAgentConfig.import":
      return runtime.importExternalAgentConfig(p);
    case "externalAgentConfig.history.record":
      return runtime.recordExternalAgentConfigHistory(p);
    case "externalAgentConfig.histories.read":
      return runtime.readExternalAgentConfigHistories();
    case "review.start":
      return runtime.startReview(p);
    case "environment.add":
      return runtime.addEnvironment(p);
    case "environment.info":
      return runtime.readEnvironmentInfo(p);
    case "environment.status":
      return runtime.readEnvironmentStatus(p);
    case "remoteControl.enable":
      return runtime.enableRemoteControl(p);
    case "remoteControl.disable":
      return runtime.disableRemoteControl(p);
    case "remoteControl.status.read":
      return runtime.readRemoteControlStatus();
    case "remoteControl.clients.list":
      return runtime.listRemoteControlClients(p);
    case "remoteControl.clients.revoke":
      return runtime.revokeRemoteControlClients(p);
    case "models.list":
      return runtime.listModels(p);
    case "models.providerCapabilities.read":
      return runtime.readModelProviderCapabilities(p);
    case "experimental.list":
      return runtime.listExperimentalFeatures(p);
    case "experimental.set":
      return runtime.setExperimentalFeature(p);
    case "permissionProfiles.list":
      return runtime.listPermissionProfiles(p);
    case "collaborationModes.list":
      return runtime.listCollaborationModes(p);
    case "windowsSandbox.setup.start":
      return runtime.startWindowsSandboxSetup(p);
    case "windowsSandbox.readiness":
      return runtime.readWindowsSandboxReadiness();
  }
}
