// Cross-tool branch interop. Detects branches + worktrees created by
// other AI coding tools so a Zeros user can see and adopt them.
// The tool ids below are the `DetectedTool` values persisted on a
// workspace row, so they are contract, not cosmetics.
//
// Detection is best-effort and layered:
//
//   1. Read every linked worktree from `git worktree list --porcelain`.
//      Zeros's own worktrees are recognised from the engine state DB /
//      managed worktree root (the in-tree .zeros/workspace.json marker was
//      retired). Other tools are still probed by a known marker file:
//        - <wt>/.cursor/worktrees.json        → cursor
//        - <wt>/.superset/config.json         → superset
//        - <wt>/.conductor/*                  → conductor
//   2. For branches that aren't checked out anywhere, fall back to
//      naming heuristics:
//        - "zeros/*"                          → zeros
//        - "cursor/*"                         → cursor
//        - single-word city name              → conductor
//        - others                             → unknown
//   3. User-level marker files are checked independently for integrations
//      that do not write state inside the worktree.

import { existsSync } from "node:fs";
import { realpath } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";

import { GitError } from "./errors";
import { generateWorkspaceId } from "./naming";
import { runGit, assertSafeGitRef } from "./git-exec";
import { refExists } from "./default-branch";
import {
  finishWorkspaceLifecycle,
  getWorkspaceByBranch,
  getWorkspaceById,
  getWorkspaceByPath,
  insertWorkspaceWithMetadata,
  insertWorkspaceWithLifecycle,
  isManagedWorktreePath,
  WORKSPACE_OWNERSHIP_META_KEY,
  updateWorkspace,
  updateWorkspaceLifecyclePhase,
  writeWorktreeSeed,
} from "./state";
import { isRepo, readOriginUrl, repoSlugFromOriginUrl } from "./repo";
import {
  clearWorkspaceBranchOwnershipMarker,
  createOwnedWorkspaceBranch,
  getWorkspace,
  getWorkspaceLifecycleStatus,
  managedWorkspacePath,
  rollbackIncompleteWorkspace,
  seedWorktreeFiles,
} from "./worktree";
import { resolveRepoGit } from "../settings/repo-git";
import type { Branch, DetectedTool, Workspace } from "./types";

// Single-word city names are a weak signal that a branch was generated by
// another tool's auto-namer rather than typed by a human. Used only when a
// branch has no marker file; a subset is enough because a miss just falls
// through to "unknown".
const CITY_NAME_HEURISTIC = new Set([
  "tokyo",
  "warsaw",
  "delhi",
  "rome",
  "paris",
  "berlin",
  "madrid",
  "vienna",
  "athens",
  "oslo",
  "dublin",
  "moscow",
  "beijing",
  "seoul",
  "sydney",
  "cairo",
  "lisbon",
  "prague",
  "kyoto",
  "boston",
  "denver",
  "houston",
  "miami",
  "phoenix",
  "portland",
  "seattle",
  "austin",
  "atlanta",
  "toronto",
  "vancouver",
  "montreal",
  "amsterdam",
  "barcelona",
  "milan",
  "munich",
  "zurich",
  "geneva",
  "helsinki",
  "stockholm",
  "copenhagen",
  "reykjavik",
  "edinburgh",
  "manchester",
  "liverpool",
  "bristol",
  "cambridge",
  "oxford",
  "brighton",
  "leeds",
  "york",
  "bath",
  "lisbon",
  "porto",
  "naples",
  "florence",
  "venice",
  "bologna",
  "geneva",
  "lyon",
  "bordeaux",
  "marseille",
  "nice",
  "cannes",
  "monaco",
  "valencia",
  "seville",
  "granada",
  "bilbao",
  "santiago",
  "valparaiso",
  "havana",
  "panama",
  "bogota",
  "lima",
  "quito",
  "caracas",
  "buenos-aires",
  "rio",
  "saopaulo",
  "salvador",
]);

interface ParsedWorktreeEntry {
  path: string;
  head: string;
  branch: string | null;
  isBare: boolean;
  isDetached: boolean;
  isLocked: boolean;
}

/** Parse the output of `git worktree list --porcelain`. The format is
 *  blank-line-separated records, each like:
 *
 *    worktree /path/to/main
 *    HEAD 0000abcdef0123...
 *    branch refs/heads/main
 *
 *    worktree /path/to/linked
 *    HEAD 1111abcdef0123...
 *    branch refs/heads/feature-x
 *
 *  Bare and detached worktrees use slightly different fields; we
 *  preserve the metadata so callers can decide what to surface. */
function parseWorktreeList(out: string): ParsedWorktreeEntry[] {
  const entries: ParsedWorktreeEntry[] = [];
  let current: Partial<ParsedWorktreeEntry> | null = null;
  for (const line of out.split("\n")) {
    if (line === "") {
      if (current && current.path) {
        entries.push({
          path: current.path,
          head: current.head ?? "",
          branch: current.branch ?? null,
          isBare: current.isBare ?? false,
          isDetached: current.isDetached ?? false,
          isLocked: current.isLocked ?? false,
        });
      }
      current = null;
      continue;
    }
    if (line.startsWith("worktree ")) {
      current = { path: line.slice("worktree ".length) };
    } else if (current && line.startsWith("HEAD ")) {
      current.head = line.slice("HEAD ".length);
    } else if (current && line.startsWith("branch ")) {
      // Strip "refs/heads/" prefix.
      current.branch = line.slice("branch refs/heads/".length);
    } else if (current && line === "bare") {
      current.isBare = true;
    } else if (current && line === "detached") {
      current.isDetached = true;
    } else if (current && line === "locked") {
      current.isLocked = true;
    }
  }
  if (current && current.path) {
    entries.push({
      path: current.path,
      head: current.head ?? "",
      branch: current.branch ?? null,
      isBare: current.isBare ?? false,
      isDetached: current.isDetached ?? false,
      isLocked: current.isLocked ?? false,
    });
  }
  return entries;
}

/** Detect which tool owns a worktree. Zeros comes FIRST so our own worktrees are
 *  never misclassified: identified from the registry (a registered workspace
 *  path) OR structurally (the worktree lives under the Zeros-managed worktrees
 *  root). The in-tree `.zeros/workspace.json` marker was retired;
 *  isManagedWorktreePath realpaths both sides so symlinked roots
 *  (macOS /var↔/private/var) still match. Other tools use their in-tree markers. */
function detectByWorktreePath(p: string): DetectedTool {
  if (getWorkspaceByPath(p) || isManagedWorktreePath(p)) return "zeros";
  if (existsSync(path.join(p, ".cursor", "worktrees.json"))) return "cursor";
  if (existsSync(path.join(p, ".superset", "config.json"))) return "superset";
  // Some tools write no per-worktree marker file at all and are only
  // identifiable by the user-tree directory they nest their worktrees in.
  // Check those path shapes before falling through to the state files.
  if (
    p.includes(`${path.sep}.conductor${path.sep}`) ||
    p.includes(`${path.sep}conductor${path.sep}`)
  ) {
    return "conductor";
  }
  // This integration keeps state outside the repo, keyed by the worktree's
  // basename in a user-level registry.
  const handle = path.basename(p);
  const workmuxState = path.join(
    homedir(),
    ".local",
    "state",
    "workmux",
    "agents",
    `${handle}.json`,
  );
  if (existsSync(workmuxState)) return "workmux";
  return "unknown";
}

/** Detect by branch name when there's no worktree (the branch is in
 *  the ref store but isn't checked out anywhere). Approximation only —
 *  the real owner could be anyone. */
function detectByBranchName(name: string): DetectedTool {
  if (name.startsWith("zeros/")) return "zeros";
  if (name.startsWith("cursor/")) return "cursor";
  if (CITY_NAME_HEURISTIC.has(name.toLowerCase())) return "conductor";
  return "unknown";
}

export interface ListAllBranchesOptions {
  repoSlug: string;
  /** Absolute path to the main worktree (repo root). Used as the
   *  source for `git worktree list`. */
  repoRoot: string;
}

export async function listAllBranches(
  opts: ListAllBranchesOptions,
): Promise<Branch[]> {
  if (!(await isRepo(opts.repoRoot))) {
    throw new GitError({
      code: "NOT_A_REPO",
      message: `${opts.repoRoot} is not a git repository`,
    });
  }
  const { stdout: wtOut } = await runGit(opts.repoRoot, [
    "worktree",
    "list",
    "--porcelain",
  ]);
  const worktrees = parseWorktreeList(wtOut);

  // Build a map of branch → { worktreePath, origin }.
  const byBranch = new Map<
    string,
    { worktreePath: string | null; origin: DetectedTool }
  >();
  for (const wt of worktrees) {
    if (!wt.branch) continue;
    const origin = detectByWorktreePath(wt.path);
    byBranch.set(wt.branch, { worktreePath: wt.path, origin });
  }

  // List all branches the repo knows about.
  const { stdout: branchOut } = await runGit(opts.repoRoot, [
    "for-each-ref",
    "--format=%(refname:short)|%(objectname)|%(committerdate:unix)",
    "refs/heads/",
  ]);

  const out: Branch[] = [];
  for (const line of branchOut.split("\n")) {
    if (!line) continue;
    const [name, tipSha, commitDateStr] = line.split("|");
    const lastCommitDate = (parseInt(commitDateStr, 10) || 0) * 1000;
    const knownWt = byBranch.get(name);

    // If this branch is checked out in one of our Zeros workspaces,
    // surface the PR URL from the DB row.
    const zerosWs = getWorkspaceByBranch(opts.repoSlug, name);

    // A DB row is PROOF this branch is ours, and it outranks the name
    // heuristic below. That matters since Settings → Git made the prefix a
    // choice: detectByBranchName still tests `zeros/` as a literal, so a
    // workspace on `jordan/Cream` or on no prefix at all used to fall through
    // to "unknown" (or, worse, to the city-name guess) and get labelled as
    // another tool's branch in the branch list. Checking the row first is
    // exact rather than heuristic, and costs nothing — it was already read.
    const origin =
      knownWt?.origin ?? (zerosWs ? "zeros" : detectByBranchName(name));

    out.push({
      name,
      tipSha,
      isCheckedOut: !!knownWt,
      worktreePath: knownWt?.worktreePath ?? null,
      origin,
      lastCommitDate,
      prUrl: zerosWs?.prUrl ?? null,
    });
  }
  out.sort((a, b) => b.lastCommitDate - a.lastCommitDate);
  return out;
}

export interface CreateWorkspaceFromBranchOptions {
  repoRoot: string;
  /** The project registry's stable slug. Required by local-only repositories
   * that have no remote URL from which one can be derived. */
  repoSlug?: string;
  branchName: string;
  /** Optional hint about which tool created the branch — used by the
   *  renderer for analytics / UI labels. Doesn't affect behavior. */
  sourceTool?: DetectedTool;
  /** When opening an EXISTING PR by its head branch, attach the PR to the new
   *  workspace so the Review tab loads it immediately (and "Create draft PR"
   *  doesn't fire a duplicate that GitHub 422s). */
  prNumber?: number;
  prUrl?: string | null;
  /** Seed gitignored config files (files-to-copy) from the main checkout into
   *  the new worktree, like createWorkspace does. Defaults ON for the local
   *  desktop; the REMOTE path passes false — a paired device must not trigger a
   *  settings-driven file copy through the same createWorkspace gate. */
  seedFiles?: boolean;
}

export interface CreateWorkspaceFromBranchResult {
  workspaceId: string;
  branch: string;
  path: string;
}

interface CreateFromBranchFlight {
  promise: Promise<CreateWorkspaceFromBranchResult>;
  startedAt: number;
  prNumber?: number;
  prUrl?: string | null;
}

const createFromBranchFlights = new Map<string, CreateFromBranchFlight>();

function createFromBranchFlightKey(
  repoRoot: string,
  branchName: string,
): string {
  return `${path.resolve(repoRoot)}\0${branchName}`;
}

export interface CreateWorkspaceFromBranchStatus {
  active: boolean;
  operation: "create" | "archive" | "restore" | "delete" | null;
  phase: string | null;
  startedAt: number | null;
  workspace: Workspace | null;
}

/** Exact repo+branch observation for a local renderer whose create-from-branch
 * request timed out before it received the generated workspace id. This covers
 * the pre-journal fetch phase, a hidden durable create row, final publication,
 * and a hard rollback without relying on elapsed time. */
export function getCreateWorkspaceFromBranchStatus(args: {
  repoRoot: string;
  repoSlug: string;
  branchName: string;
}): CreateWorkspaceFromBranchStatus {
  const flight = createFromBranchFlights.get(
    createFromBranchFlightKey(args.repoRoot, args.branchName),
  );
  const candidate = getWorkspaceByBranch(args.repoSlug, args.branchName);
  const row =
    candidate &&
    path.resolve(candidate.repoRoot) === path.resolve(args.repoRoot)
      ? getWorkspace(candidate.id)
      : null;
  const lifecycle = row
    ? getWorkspaceLifecycleStatus(row.id)
    : {
        active: false,
        operation: null,
        phase: null,
        startedAt: null,
      };
  return {
    active: flight != null || lifecycle.active,
    operation: flight ? "create" : lifecycle.operation,
    phase: lifecycle.phase,
    startedAt: lifecycle.startedAt ?? flight?.startedAt ?? null,
    workspace: row,
  };
}

/** Create a Zeros workspace that points at an existing branch. Useful
 *  when the user wants to adopt a branch another tool created without
 *  losing the work.
 *
 *  We don't move the branch — we add a new worktree under the visible
 *  <workspaces>/<repository>/<branch-name> layout. If the branch is already
 *  checked out in another worktree, we surface BRANCH_IN_USE so the
 *  renderer can offer the standard 3-option flow (switch / fork /
 *  archive other). */
export function createWorkspaceFromBranch(
  opts: CreateWorkspaceFromBranchOptions,
): Promise<CreateWorkspaceFromBranchResult> {
  const key = createFromBranchFlightKey(opts.repoRoot, opts.branchName);
  const active = createFromBranchFlights.get(key);
  if (active) {
    if (typeof opts.prNumber === "number") {
      active.prNumber = opts.prNumber;
      active.prUrl = opts.prUrl ?? null;
    }
    return active.promise;
  }
  const startedAt = Date.now();
  const flight: CreateFromBranchFlight = {
    startedAt,
    ...(typeof opts.prNumber === "number"
      ? { prNumber: opts.prNumber, prUrl: opts.prUrl ?? null }
      : {}),
    promise: createWorkspaceFromBranchInner(opts)
      .then((result) => {
        // Another renderer may have opened the PR while this same branch create
        // was already running. Preserve one checkout/promise while still
        // merging the richer PR identity before the shared response is
        // published.
        if (typeof flight.prNumber === "number") {
          updateWorkspace(result.workspaceId, {
            status: "in-review",
            prNumber: flight.prNumber,
            prUrl: flight.prUrl ?? null,
          });
        }
        return result;
      })
      .finally(() => {
        if (createFromBranchFlights.get(key) === flight) {
          createFromBranchFlights.delete(key);
        }
      }),
  };
  createFromBranchFlights.set(key, flight);
  return flight.promise;
}

async function createWorkspaceFromBranchInner(
  opts: CreateWorkspaceFromBranchOptions,
): Promise<CreateWorkspaceFromBranchResult> {
  if (!(await isRepo(opts.repoRoot))) {
    throw new GitError({
      code: "NOT_A_REPO",
      message: `${opts.repoRoot} is not a git repository`,
    });
  }
  // `branchName` becomes a positional / `-b` arg + is interpolated into
  // `<remote>/<branch>` below — reject a leading-"-" (flag injection) up front.
  assertSafeGitRef(opts.branchName, "branchName");
  // The repo's configured `git.remote` (default "origin") — the same remote
  // the create path fetches/forks from. Settings-sourced → guard it too.
  const { remote } = resolveRepoGit(opts.repoRoot);
  assertSafeGitRef(remote, "remote");
  // The branch may exist LOCALLY (adopting another tool's branch) or ONLY on
  // the remote (opening a teammate's PR we've never fetched). Resolve which.
  const localExists = await refExists(
    opts.repoRoot,
    `refs/heads/${opts.branchName}`,
  );
  let fromRemote = false;
  if (!localExists) {
    // Fetch the single branch so its remote-tracking ref is present + current,
    // then check it. Best-effort: offline / no-such-branch falls to the guard.
    try {
      // Bounded so a slow/hung remote fails cleanly here rather than outlasting
      // the (30s) createFromBranch RPC and orphaning a half-made worktree — this
      // fetch precedes `worktree add`. Mirrors the create path's bounded fetch.
      await runGit(opts.repoRoot, ["fetch", remote, opts.branchName], {
        timeoutMs: 20_000,
      });
    } catch {
      /* offline or no such remote branch — the ref check below decides */
    }
    if (
      await refExists(
        opts.repoRoot,
        `refs/remotes/${remote}/${opts.branchName}`,
      )
    ) {
      fromRemote = true;
    } else {
      throw new GitError({
        code: "VALIDATION_FAILED",
        message: `Branch "${opts.branchName}" does not exist locally or on ${remote} in ${opts.repoRoot}`,
      });
    }
  }
  // Prefer the project registry's stable slug. This is load-bearing for a
  // local-only repository with no remote, and also keeps path-derived project
  // identity aligned with ordinary workspace creation. Older callers may omit
  // it, in which case derive from origin/configured remote as before.
  let repoSlug = opts.repoSlug ?? "";
  if (repoSlug) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(repoSlug) || repoSlug.includes("..")) {
      throw new GitError({
        code: "VALIDATION_FAILED",
        message: `Invalid repository slug "${repoSlug}"`,
      });
    }
  } else {
    let originUrl: string;
    try {
      originUrl = await readOriginUrl(opts.repoRoot);
    } catch (err) {
      if (remote === "origin") throw err;
      const { stdout } = await runGit(opts.repoRoot, [
        "remote",
        "get-url",
        remote,
      ]);
      originUrl = stdout.trim();
    }
    repoSlug = repoSlugFromOriginUrl(originUrl);
  }
  // Do not create a second workspace row for a branch that already
  // has one. Without this, adopting a branch that maps to an *archived*
  // Zeros workspace inserts a duplicate active row pointing at a
  // different path — divergent state for the same branch.
  const existing = getWorkspaceByBranch(repoSlug, opts.branchName);
  if (existing) {
    throw new GitError({
      code: "WORKSPACE_ALREADY_EXISTS",
      message: `A workspace for branch "${opts.branchName}" already exists (status=${existing.status}).`,
      remediation:
        existing.archivedAt != null
          ? "Restore the archived workspace instead of creating a new one."
          : "Switch to the existing workspace instead of creating a new one.",
      context: { workspaceId: existing.id, status: existing.status },
    });
  }
  // Derive a base branch for the adopted branch: the repo's configured
  // `git.base_branch` when it resolves (locally or as a remote-tracking ref),
  // else "main" if that exists, else track the branch itself. Adopted branches
  // predate Zeros, so this is a best guess the target-branch picker can fix.
  const { baseBranch: settingBase } = resolveRepoGit(opts.repoRoot);
  let baseBranch = opts.branchName;
  for (const candidate of settingBase === "main"
    ? ["main"]
    : [settingBase, "main"]) {
    if (
      (await refExists(opts.repoRoot, `refs/heads/${candidate}`)) ||
      (await refExists(opts.repoRoot, `refs/remotes/${remote}/${candidate}`))
    ) {
      baseBranch = candidate;
      break;
    }
  }
  const workspaceId = generateWorkspaceId(opts.branchName);
  const baseWorkspacePath = managedWorkspacePath(
    opts.repoRoot,
    repoSlug,
    opts.branchName,
  );
  let workspacePath = baseWorkspacePath;
  for (
    let suffix = 2;
    (existsSync(workspacePath) || getWorkspaceByPath(workspacePath)) &&
    suffix < 100;
    suffix++
  ) {
    workspacePath = `${baseWorkspacePath}-${suffix}`;
  }
  if (existsSync(workspacePath) || getWorkspaceByPath(workspacePath)) {
    throw new GitError({
      code: "WORKSPACE_ALREADY_EXISTS",
      message: `No free workspace folder is available near ${baseWorkspacePath}`,
    });
  }
  // Base-branch/ref resolution above yielded to other lifecycle requests.
  // Reserve only after rechecking the branch/id synchronously; the engine is a
  // single SQLite writer, so no competing row can interleave before insert.
  if (
    getWorkspaceById(workspaceId) ||
    getWorkspaceByBranch(repoSlug, opts.branchName)
  ) {
    throw new GitError({
      code: "WORKSPACE_ALREADY_EXISTS",
      message: `A workspace for branch "${opts.branchName}" was created concurrently.`,
      remediation:
        "Switch to the existing workspace, or refresh and duplicate the branch.",
    });
  }

  // Reserve the row and durable create intent before Git mutates either the
  // worktree registry or a remote-only local branch. Create-journal rows are
  // intentionally excluded from workspace.list until the checkout is ready.
  const hasPr = typeof opts.prNumber === "number";
  const now = Date.now();
  const ws: Workspace = {
    id: workspaceId,
    repoSlug,
    repoRoot: opts.repoRoot,
    branch: opts.branchName,
    baseBranch,
    path: workspacePath,
    status: hasPr ? "in-review" : "in-progress",
    createdAt: now,
    archivedAt: null,
    stashRef: null,
    archivedHead: null,
    archiveSnapshot: null,
    prNumber: hasPr ? (opts.prNumber as number) : null,
    prState: null,
    prUrl: opts.prUrl ?? null,
    agentId: null,
    lastActiveAt: now,
    setupState: null,
  };
  insertWorkspaceWithLifecycle(ws, {
    workspaceId,
    operation: "create",
    phase: "prepared",
    sourcePath: workspacePath,
    targetPath: workspacePath,
    sourceBranch: opts.branchName,
    targetBranch: opts.branchName,
    createFrom: fromRemote ? `${remote}/${opts.branchName}` : opts.branchName,
    archiveSnapshot: null,
    archivedHead: null,
    adaptations: [],
    payload: {
      fromBranch: true,
      branchCreatedByOperation: fromRemote,
      seedFiles: opts.seedFiles !== false,
    },
    includeBranch: fromRemote,
    startedAt: now,
  });

  // Create a remote-only local branch as a separate atomic step, for the same
  // ownership reason as ordinary create: if another process wins the branch
  // race, rollback must not delete its ref.
  let branchCreated = false;
  try {
    if (fromRemote) {
      await createOwnedWorkspaceBranch({
        repoRoot: opts.repoRoot,
        workspaceId,
        branch: opts.branchName,
        startPoint: `${remote}/${opts.branchName}`,
      });
      branchCreated = true;
      await runGit(opts.repoRoot, [
        "branch",
        "--set-upstream-to",
        `${remote}/${opts.branchName}`,
        opts.branchName,
      ]);
      updateWorkspaceLifecyclePhase(workspaceId, "branch-created");
    }
    await runGit(
      opts.repoRoot,
      ["worktree", "add", workspacePath, opts.branchName],
      {
        mapErrorCode: (stderr) => {
          if (/already used by worktree|is already checked out/i.test(stderr)) {
            return "BRANCH_IN_USE";
          }
          return "GIT_COMMAND_FAILED";
        },
      },
    );
    updateWorkspaceLifecyclePhase(workspaceId, "worktree-created");
  } catch (err) {
    const rolledBack = await rollbackIncompleteWorkspace({
      repoRoot: opts.repoRoot,
      worktreePath: workspacePath,
      workspaceId,
      expectedBranch: opts.branchName,
      ...(branchCreated ? { branchToDelete: opts.branchName } : {}),
    });
    if (!rolledBack) {
      throw new GitError({
        code: "GIT_COMMAND_FAILED",
        message: `Couldn't safely roll back the incomplete workspace at ${workspacePath}`,
        cause: err,
        remediation:
          "The hidden recovery record was retained. Close processes using the folder and restart Zeros to finish cleanup.",
      });
    }
    throw err;
  }

  // Files-to-copy parity with createWorkspace: a from-branch / open-PR
  // workspace used to start with NO gitignored config at all (no .env, no
  // .worktreeinclude seeds) — the branch checkout only brings tracked files.
  // Same guarantees as create: bounded sync scan, background completion when
  // cut short, and a file the BRANCH committed at a seed path is never
  // clobbered. Local-only (the remote path passes seedFiles: false).
  try {
    if (opts.seedFiles !== false) {
      await seedWorktreeFiles({
        workspaceId,
        repoRoot: opts.repoRoot,
        worktreePath: workspacePath,
      });
    }

    updateWorkspaceLifecyclePhase(workspaceId, "work-applied");
    // Crash-recovery seed → app-data (not the worktree's working tree).
    writeWorktreeSeed(ws);
    finishWorkspaceLifecycle(workspaceId, {});
    await clearWorkspaceBranchOwnershipMarker(opts.repoRoot, workspaceId);
  } catch (err) {
    const rolledBack = await rollbackIncompleteWorkspace({
      repoRoot: opts.repoRoot,
      worktreePath: workspacePath,
      workspaceId,
      expectedBranch: opts.branchName,
      ...(branchCreated ? { branchToDelete: opts.branchName } : {}),
    });
    if (!rolledBack) {
      throw new GitError({
        code: "GIT_COMMAND_FAILED",
        message: `Couldn't safely roll back the incomplete workspace at ${workspacePath}`,
        cause: err,
        remediation:
          "The hidden recovery record was retained. Close processes using the folder and restart Zeros to finish cleanup.",
      });
    }
    throw err;
  }

  return {
    workspaceId,
    branch: opts.branchName,
    path: workspacePath,
  };
}

export interface AdoptExistingWorktreeOptions {
  /** The PRIMARY checkout (main working tree) — becomes the project root, so
   *  the adopted workspace joins the same project as Local main. */
  repoRoot: string;
  /** The existing foreign worktree directory to adopt in place (stays put). */
  worktreePath: string;
  /** The branch checked out in `worktreePath`. */
  branchName: string;
  /** The slug the caller already assigned to the project. When set, the
   *  workspace uses it verbatim so the two ALWAYS agree — critical for
   *  no-origin repos, where the slug is derived from the path, not the remote.
   *  Falls back to deriving from origin when omitted. */
  repoSlug?: string;
  sourceTool?: DetectedTool;
}

const adoptWorktreeFlights = new Map<
  string,
  Promise<CreateWorkspaceFromBranchResult>
>();

/** Adopt an EXISTING linked worktree (created by another tool, living at an
 *  arbitrary path) as a Zeros workspace — WITHOUT running `git worktree add`.
 *  The worktree already exists on disk and stays where it is; we only register
 *  a DB row pointing at it (the same mechanic crash-recovery uses to re-seed an
 *  orphaned worktree). Idempotent on the worktree path. */
export function adoptExistingWorktree(
  opts: AdoptExistingWorktreeOptions,
): Promise<CreateWorkspaceFromBranchResult> {
  const key = path.resolve(opts.worktreePath);
  const active = adoptWorktreeFlights.get(key);
  if (active) return active;
  const promise = adoptExistingWorktreeInner(opts).finally(() => {
    if (adoptWorktreeFlights.get(key) === promise) {
      adoptWorktreeFlights.delete(key);
    }
  });
  adoptWorktreeFlights.set(key, promise);
  return promise;
}

async function adoptExistingWorktreeInner(
  opts: AdoptExistingWorktreeOptions,
): Promise<CreateWorkspaceFromBranchResult> {
  if (!(await isRepo(opts.repoRoot))) {
    throw new GitError({
      code: "NOT_A_REPO",
      message: `${opts.repoRoot} is not a git repository`,
    });
  }
  if (!existsSync(opts.worktreePath)) {
    throw new GitError({
      code: "VALIDATION_FAILED",
      message: `Worktree path no longer exists: ${opts.worktreePath}`,
    });
  }
  // Prefer the slug the caller assigned to the project so the workspace always
  // shares it (no-origin repos derive the slug from the path, not the remote).
  // Fall back to deriving from origin for older callers.
  const repoSlug =
    opts.repoSlug || repoSlugFromOriginUrl(await readOriginUrl(opts.repoRoot));

  // Idempotent: if this exact worktree is already tracked, return it as-is.
  const existingByPath = getWorkspaceByPath(opts.worktreePath);
  if (existingByPath) {
    return {
      workspaceId: existingByPath.id,
      branch: existingByPath.branch,
      path: existingByPath.path,
    };
  }
  // Don't create a second row for a branch that already has a workspace.
  const existingByBranch = getWorkspaceByBranch(repoSlug, opts.branchName);
  if (existingByBranch) {
    throw new GitError({
      code: "WORKSPACE_ALREADY_EXISTS",
      message: `A workspace for branch "${opts.branchName}" already exists (status=${existingByBranch.status}).`,
      remediation:
        existingByBranch.archivedAt != null
          ? "Restore the archived workspace instead of adopting it again."
          : "Switch to the existing workspace instead of adopting it again.",
      context: {
        workspaceId: existingByBranch.id,
        status: existingByBranch.status,
      },
    });
  }
  // Revalidate the discovery result at mutation time: the directory must still
  // be the root of a linked worktree owned by this repository and still have the
  // branch the user selected. This prevents a stale picker row from registering
  // an unrelated/replaced folder.
  let topLevel: string;
  let sourceCommon: string;
  let targetCommon: string;
  try {
    const results = await Promise.all([
      runGit(opts.worktreePath, ["rev-parse", "--show-toplevel"]),
      runGit(opts.repoRoot, ["rev-parse", "--git-common-dir"]),
      runGit(opts.worktreePath, ["rev-parse", "--git-common-dir"]),
    ]);
    topLevel = results[0].stdout;
    sourceCommon = results[1].stdout;
    targetCommon = results[2].stdout;
  } catch (error) {
    throw new GitError({
      code: "VALIDATION_FAILED",
      message: `${opts.worktreePath} is no longer a valid linked worktree`,
      cause: error,
      remediation: "Refresh the detected worktree list and choose it again.",
    });
  }
  const resolveGitPath = (cwd: string, value: string): string =>
    path.resolve(cwd, value.trim());
  const canonicalPath = async (value: string): Promise<string> =>
    realpath(value).catch(() => path.resolve(value));
  const [actualTop, expectedTop, actualCommon, expectedCommon] =
    await Promise.all([
      canonicalPath(topLevel.trim()),
      canonicalPath(opts.worktreePath),
      canonicalPath(resolveGitPath(opts.worktreePath, targetCommon)),
      canonicalPath(resolveGitPath(opts.repoRoot, sourceCommon)),
    ]);
  if (actualTop !== expectedTop || actualCommon !== expectedCommon) {
    throw new GitError({
      code: "VALIDATION_FAILED",
      message: `${opts.worktreePath} is not a linked worktree of ${opts.repoRoot}`,
      remediation: "Refresh the detected worktree list and choose it again.",
    });
  }
  const { stdout: actualBranch } = await runGit(opts.worktreePath, [
    "branch",
    "--show-current",
  ]);
  if (actualBranch.trim() !== opts.branchName) {
    throw new GitError({
      code: "VALIDATION_FAILED",
      message: `Worktree branch changed from "${opts.branchName}" to "${actualBranch.trim() || "detached HEAD"}"`,
      remediation: "Refresh the detected worktree list and choose it again.",
    });
  }
  // Base branch: prefer main if it exists, else track the branch itself.
  let baseBranch = "main";
  try {
    await runGit(opts.repoRoot, [
      "show-ref",
      "--verify",
      "--quiet",
      "refs/heads/main",
    ]);
  } catch {
    baseBranch = opts.branchName;
  }
  // The Git identity/base checks above are asynchronous. Recheck exact row
  // ownership immediately before publication so two stale picker actions
  // cannot register the same path/branch under distinct workspace ids.
  const concurrentPathOwner = getWorkspaceByPath(opts.worktreePath);
  if (concurrentPathOwner) {
    return {
      workspaceId: concurrentPathOwner.id,
      branch: concurrentPathOwner.branch,
      path: concurrentPathOwner.path,
    };
  }
  const concurrentBranchOwner = getWorkspaceByBranch(repoSlug, opts.branchName);
  if (concurrentBranchOwner) {
    throw new GitError({
      code: "WORKSPACE_ALREADY_EXISTS",
      message: `A workspace for branch "${opts.branchName}" was registered concurrently.`,
      remediation: "Switch to the existing workspace instead.",
      context: { workspaceId: concurrentBranchOwner.id },
    });
  }
  const workspaceId = generateWorkspaceId(opts.branchName);
  const now = Date.now();
  const ws: Workspace = {
    id: workspaceId,
    repoSlug,
    repoRoot: opts.repoRoot,
    branch: opts.branchName,
    baseBranch,
    // The worktree's real, external location — NOT under worktreesRoot().
    path: opts.worktreePath,
    status: "in-progress",
    createdAt: now,
    archivedAt: null,
    stashRef: null,
    prNumber: null,
    prState: null,
    prUrl: null,
    agentId: null,
    lastActiveAt: now,
  };
  insertWorkspaceWithMetadata(ws, {
    [WORKSPACE_OWNERSHIP_META_KEY]: "adopted",
  });
  writeWorktreeSeed(ws);

  return {
    workspaceId,
    branch: opts.branchName,
    path: opts.worktreePath,
  };
}
