// Five-story dot-matrix motion data for the agent "thinking" tail indicator.
//
// Ported 1:1 from the approved `shape shimmer/` prototype (story-poses.js):
// five 12×12 mask-authored scenes — cat + mouse, rolling eyes, rower + boat,
// train + steam, mountain sunrise — each expanded at module load into 16
// smoothstep-blended action frames plus a 4-frame diagonal relay wipe into
// the next scene (100 frames total, one 8s loop).
//
// The matrix is authored 24px-first: 12 columns give an exact 2px dot pitch
// inside a 24 × 24 canvas, so every silhouette stays readable at true size.
// Only storytelling landmarks (legs, pupils, oar, steam, the rising sun)
// move between key poses; each silhouette otherwise stays fixed.

const GRID_WIDTH = 12;
const GRID_HEIGHT = 12;
const ACTION_FRAMES = 16;
const TRANSITION_FRAMES = 4;

export const STORY_SHIMMER_VIEW_SIZE = 12;
export const STORY_SHIMMER_SCENE_COUNT = 5;
export const STORY_SHIMMER_SCENE_FRAME_COUNT =
  ACTION_FRAMES + TRANSITION_FRAMES;

/** Approved loop tuning — mirrors the prototype lab defaults. */
export const STORY_SHIMMER_MOTION_DEFAULTS = Object.freeze({
  cycleDurationMs: 8000,
  dotRadius: 0.4,
  dotScale: 1,
  frameBlend: true,
  shimmerIntensity: 0.9,
  speed: 1,
});

/** Rendering constants for the tiny thinking-indicator treatment. */
export const STORY_SHIMMER_MICRO_DEFAULTS = Object.freeze({
  /** The authored target size — a 2px dot pitch on the 12-column grid. */
  cssSizePx: 24,
  /** At or below this square CSS size, dot centers snap to the
   *  physical-pixel grid so neighboring Retina dots stay separated. */
  maxMicroCssSizePx: 32,
  /** Radius floor at micro sizes (CSS px). */
  minimumMicroCssRadiusPx: 0.36,
  /** Radius floor at larger sizes (physical px, divided by DPR). */
  minimumPhysicalRadiusPx: 0.52,
});

/** `#` regular dot, `O` landmark (paws, pupils, wheels, oar tip, the sun),
 *  `o` small support dot (tails, steam, water, rays). */
const CHARACTER_RADIUS: Readonly<Record<string, number>> = Object.freeze({
  "#": 1,
  O: 1.3,
  o: 0.8,
});

export interface StoryShimmerPoseDot {
  readonly alpha: number;
  readonly radius: number;
  readonly x: number;
  readonly y: number;
}

export interface StoryShimmerTransitionDot {
  readonly fromAlpha: number;
  readonly fromRadius: number;
  readonly toAlpha: number;
  readonly toRadius: number;
  readonly x: number;
  readonly y: number;
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.min(maximum, Math.max(minimum, value));
}

function smoothstep(value: number): number {
  const progress = clamp(value, 0, 1);
  return progress * progress * (3 - 2 * progress);
}

function rows(value: string, label: string): string[] {
  const result = value.trim().split("\n");
  if (result.length !== GRID_HEIGHT) {
    throw new Error(
      `${label} must have ${GRID_HEIGHT} rows; received ${result.length}.`,
    );
  }
  for (const [index, row] of result.entries()) {
    if (row.length !== GRID_WIDTH) {
      throw new Error(
        `${label} row ${index + 1} must have ${GRID_WIDTH} cells; received ${row.length}.`,
      );
    }
  }
  return result;
}

function cellsFromMasks(
  label: string,
  ...masks: string[][]
): StoryShimmerPoseDot[] {
  const cells = new Map<string, StoryShimmerPoseDot>();
  for (const mask of masks) {
    for (let y = 0; y < mask.length; y += 1) {
      for (let x = 0; x < mask[y].length; x += 1) {
        const character = mask[y][x];
        const radius = CHARACTER_RADIUS[character];
        if (radius === undefined) continue;
        const key = `${x}:${y}`;
        const existing = cells.get(key);
        if (!existing || radius > existing.radius) {
          cells.set(key, {
            alpha: 1,
            radius,
            x: x - (GRID_WIDTH - 1) / 2,
            y: y - (GRID_HEIGHT - 1) / 2,
          });
        }
      }
    }
  }
  if (cells.size === 0) throw new Error(`${label} produced an empty pose.`);
  return [...cells.values()].sort(
    (first, second) => first.y - second.y || first.x - second.x,
  );
}

function poseSet(
  sceneId: string,
  baseSource: string,
  motionSources: string[],
): StoryShimmerPoseDot[][] {
  const base = rows(baseSource, `${sceneId} base`);
  return motionSources.map((source, index) =>
    cellsFromMasks(
      `${sceneId} pose ${index + 1}`,
      base,
      rows(source, `${sceneId} motion ${index + 1}`),
    ),
  );
}

const catMouse = poseSet(
  "cat-mouse",
  `............
............
....#.#.....
o...###.....
.o..####....
.#######....
.######.....
..##..##....
............
..........O.
........o##o
............`,
  [
    `............
............
............
............
............
............
............
............
..#....#....
.##....##...
O.......O...
............`,
    `............
............
............
............
............
............
............
............
...#..#.....
...##.##....
....O.O.....
............`,
    `............
............
............
............
............
............
............
............
..#.....#...
.##....##...
.O.....O....
............`,
    `............
............
............
............
............
............
............
............
..#...#.....
..#...#.....
..O...O.....
............`,
  ],
);

const eyesRolling = poseSet(
  "eyes-rolling",
  `............
............
............
............
..##....##..
.#..#..#..#.
.#..#..#..#.
.#..#..#..#.
..##....##..
............
............
............`,
  [
    `............
............
............
............
............
..o.....o...
..O.....O...
..o.....o...
............
............
............
............`,
    `............
............
............
............
............
...o.....o..
...O.....O..
...o.....o..
............
............
............
............`,
    `............
............
............
............
............
..o.....o...
..O.....O...
..o.....o...
............
............
............
............`,
    `............
............
............
............
............
...o.....o..
...O.....O..
...o.....o..
............
............
............
............`,
  ],
);

const rowerBoat = poseSet(
  "rower-boat",
  `............
............
....O.......
...###......
...##.......
..###.......
.##########.
..########..
....####....
............
............
.o..o..o..o.`,
  [
    `..........o.
.........#..
........#...
.......#....
.....##.....
............
............
............
............
............
............
............`,
    `............
............
............
.........##O
......###...
.....#......
............
............
............
............
............
............`,
    `............
............
............
............
.....##.....
.......##...
.........#..
..........O.
............
............
............
............`,
    `............
..........o.
........##..
.......#....
.....##.....
............
............
............
............
............
............
............`,
  ],
);

const trainSteam = poseSet(
  "train-steam",
  `............
............
.......##...
.####..##...
.#..#..##...
.#..#######.
.##########O
.##########.
..O..O..O...
............
............
............`,
  [
    `......o.....
........o...
............
............
............
............
............
............
............
............
............
............`,
    `....o.......
.......O....
............
............
............
............
............
............
............
............
............
............`,
    `...o....o...
......o.....
............
............
............
............
............
............
............
............
............
............`,
    `.....o......
........o...
............
............
............
............
............
............
............
............
............
............`,
  ],
);

const mountainSunrise = poseSet(
  "mountain-sunrise",
  `............
............
............
............
............
..#......#..
.###....###.
#####..#####
############
............
............
............`,
  [
    `............
............
............
............
............
............
............
.....OO.....
............
............
............
............`,
    `............
............
............
............
............
............
.....OO.....
.....OO.....
............
............
............
............`,
    `............
............
............
............
............
.....OO.....
.....OO.....
............
............
............
............
............`,
    `............
............
.....oo.....
...o....o...
.....OO.....
.....OO.....
............
............
............
............
............
............`,
  ],
);

const SCENE_POSE_SETS: ReadonlyArray<StoryShimmerPoseDot[][]> = [
  catMouse,
  eyesRolling,
  rowerBoat,
  trainSteam,
  mountainSunrise,
];

function poseMap(pose: StoryShimmerPoseDot[]): Map<string, StoryShimmerPoseDot> {
  return new Map(pose.map((cell) => [`${cell.x}:${cell.y}`, cell]));
}

function interpolatedMotionPose(
  keyPoses: StoryShimmerPoseDot[][],
  frame: number,
): StoryShimmerPoseDot[] {
  const exactKey =
    (frame / Math.max(1, ACTION_FRAMES - 1)) * (keyPoses.length - 1);
  const fromIndex = Math.floor(exactKey);
  const toIndex = Math.min(keyPoses.length - 1, fromIndex + 1);
  const blend = smoothstep(exactKey - fromIndex);
  const from = poseMap(keyPoses[fromIndex]);
  const to = poseMap(keyPoses[toIndex]);
  const keys = new Set([...from.keys(), ...to.keys()]);
  const result: StoryShimmerPoseDot[] = [];

  for (const key of keys) {
    const fromCell = from.get(key);
    const toCell = to.get(key);
    const anchor = (fromCell ?? toCell) as StoryShimmerPoseDot;
    const alpha = (fromCell ? 1 - blend : 0) + (toCell ? blend : 0);
    if (alpha < 0.025) continue;
    result.push({
      alpha: clamp(alpha, 0, 1),
      radius:
        (fromCell?.radius ?? anchor.radius) * (1 - blend) +
        (toCell?.radius ?? anchor.radius) * blend,
      x: anchor.x,
      y: anchor.y,
    });
  }

  return result.sort(
    (first, second) => first.y - second.y || first.x - second.x,
  );
}

function relayWipePose(
  fromPose: StoryShimmerPoseDot[],
  toPose: StoryShimmerPoseDot[],
  progress: number,
): StoryShimmerPoseDot[] {
  const from = poseMap(fromPose);
  const to = poseMap(toPose);
  const keys = new Set([...from.keys(), ...to.keys()]);
  const eased = smoothstep(progress);
  const threshold = -9 + eased * 18;
  const feather = 1.2;
  const result: StoryShimmerPoseDot[] = [];

  for (const key of keys) {
    const fromCell = from.get(key);
    const toCell = to.get(key);
    const anchor = (fromCell ?? toCell) as StoryShimmerPoseDot;
    const diagonal = anchor.x + anchor.y * 0.32;
    const toAlpha = clamp((threshold - diagonal + feather) / (feather * 2), 0, 1);
    const fromAlpha = 1 - toAlpha;
    const alpha = Math.max(fromCell ? fromAlpha : 0, toCell ? toAlpha : 0);
    if (alpha < 0.04) continue;
    result.push({
      alpha,
      radius: Math.max(fromCell?.radius ?? 0, toCell?.radius ?? 0),
      x: anchor.x,
      y: anchor.y,
    });
  }

  return result.sort(
    (first, second) => first.y - second.y || first.x - second.x,
  );
}

function buildPoses(): StoryShimmerPoseDot[][] {
  const poses: StoryShimmerPoseDot[][] = [];
  for (let sceneIndex = 0; sceneIndex < SCENE_POSE_SETS.length; sceneIndex += 1) {
    const scene = SCENE_POSE_SETS[sceneIndex];
    const nextScene = SCENE_POSE_SETS[(sceneIndex + 1) % SCENE_POSE_SETS.length];
    for (let frame = 0; frame < ACTION_FRAMES; frame += 1) {
      poses.push(interpolatedMotionPose(scene, frame));
    }
    const fromPose = poses[poses.length - 1];
    for (let frame = 0; frame < TRANSITION_FRAMES; frame += 1) {
      poses.push(
        relayWipePose(fromPose, nextScene[0], (frame + 1) / (TRANSITION_FRAMES + 1)),
      );
    }
  }
  return poses;
}

function makeTransitions(
  poses: StoryShimmerPoseDot[][],
): StoryShimmerTransitionDot[][] {
  return poses.map((fromPose, poseIndex) => {
    const from = poseMap(fromPose);
    const to = poseMap(poses[(poseIndex + 1) % poses.length]);
    const keys = new Set([...from.keys(), ...to.keys()]);
    return [...keys]
      .map((key) => {
        const fromCell = from.get(key);
        const toCell = to.get(key);
        const anchor = (fromCell ?? toCell) as StoryShimmerPoseDot;
        return {
          fromAlpha: fromCell?.alpha ?? 0,
          fromRadius: (fromCell ?? anchor).radius,
          toAlpha: toCell?.alpha ?? 0,
          toRadius: (toCell ?? anchor).radius,
          x: anchor.x,
          y: anchor.y,
        };
      })
      .sort((first, second) => first.y - second.y || first.x - second.x);
  });
}

export const STORY_SHIMMER_POSES: ReadonlyArray<
  ReadonlyArray<StoryShimmerPoseDot>
> = buildPoses();

export const STORY_SHIMMER_FRAME_COUNT = STORY_SHIMMER_POSES.length;

export const STORY_SHIMMER_TRANSITIONS: ReadonlyArray<
  ReadonlyArray<StoryShimmerTransitionDot>
> = makeTransitions(STORY_SHIMMER_POSES as StoryShimmerPoseDot[][]);

/** Diagonal projection driving the traveling highlight band. Constants match
 *  the approved prototype (story-shimmer.js) so the sweep feel is identical. */
export function storyShimmerProjection(x: number, y: number): number {
  return (x + 7 + (y + 7) * 0.38) / (14 * 1.38);
}
